Update sync_cron.yml
disabled the response

diff --git a/.github/workflows/sync_cron.yml b/.github/workflows/sync_cron.yml
--- a/.github/workflows/sync_cron.yml
+++ b/.github/workflows/sync_cron.yml
@@ -5,17 +5,24 @@ on:
     - cron: "30 21 * * *"  # 3:00 AM IST
   workflow_dispatch:
 
+# jobs:
+#   sync:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Trigger Sync API
+#         run: |
+#           echo "Triggering sync..."
+#           response=$(curl -s -o response.txt -w "%{http_code}" -X POST https://klaxon-api.onrender.com/api/trigger-sync)
+#           cat response.txt
+#           if [ "$response" -ne 200 ]; then
+#             echo "❌ Sync failed with HTTP status $response"
+#             exit 1
+#           fi
+#           echo "✅ Sync triggered successfully."
 jobs:
-  sync:
+  ping:
     runs-on: ubuntu-latest
     steps:
       - name: Trigger Sync API
         run: |
-          echo "Triggering sync..."
-          response=$(curl -s -o response.txt -w "%{http_code}" -X POST https://klaxon-api.onrender.com/api/trigger-sync)
-          cat response.txt
-          if [ "$response" -ne 200 ]; then
-            echo "❌ Sync failed with HTTP status $response"
-            exit 1
-          fi
-          echo "✅ Sync triggered successfully."
+          curl -s  https://klaxon-api.onrender.com/api/trigger-sync > /dev/null
